### ISSUE TITLE
[Week 4] Twitter - Submission

### ISSUE THREAD

**Issue by DGh0st** [DGh0st/Tweety#1]
My twitter application for week 4 is complete, please review. /cc @codepathreview

**Comment by avo1** [comment]
:+1: Great work! The point of this homework was to explore an example of a full MVC application with a RESTful API. 
- You should be familiar with autoLayout now. Well done!
- Good job implementing the fav/retweet number update with nice button images, and correct API call for fav/retweet. 

We have a detailed [Project 4 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_4_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

Dave
CodePath
